template: Hello, %s!
defaultName: Stranger

server:
  rootPath: /api/v1/*
  applicationConnectors:
    - type: http
      port: 8080
#    - type: https
#      port: 8443
#      keyStorePath: test.keystore
#      keyStorePassword: test
  adminConnectors:
    - type: http
      port: 8081
#    - type: https
#      port: 8444
#      keyStorePath: test.keystore
#      keyStorePassword: test

# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:~/dropwizard-core;MODE=MYSQL

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect


# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080

logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG
  appenders:
    - type: console
#      layout:
#        type: json
